# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lucas\Documents\GitHub\ShortProjects\Python\LoginApp\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 883)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1087, 883))
        MainWindow.setMaximumSize(QtCore.QSize(1087, 883))
        MainWindow.setStyleSheet("background-color: lightgreen;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(970, 810, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_logout.setFont(font)
        self.pushButton_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_logout.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButton_inserir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inserir.setGeometry(QtCore.QRect(900, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_inserir.setFont(font)
        self.pushButton_inserir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_inserir.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_inserir.setObjectName("pushButton_inserir")
        self.pushButton_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove.setGeometry(QtCore.QRect(900, 110, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_remove.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.pushButton_relatorio = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_relatorio.setGeometry(QtCore.QRect(420, 110, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_relatorio.setFont(font)
        self.pushButton_relatorio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_relatorio.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_relatorio.setObjectName("pushButton_relatorio")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_1.setGeometry(QtCore.QRect(20, 210, 511, 571))
        self.tableWidget_1.setStyleSheet("background-color: rgb(255, 255, 255); border-radius:15px; border: 2px solid green;")
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(0)
        self.tableWidget_1.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(560, 210, 511, 571))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255); border-radius:15px; border: 2px solid green;")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_inserir, self.pushButton_relatorio)
        MainWindow.setTabOrder(self.pushButton_relatorio, self.pushButton_remove)
        MainWindow.setTabOrder(self.pushButton_remove, self.tableWidget_1)
        MainWindow.setTabOrder(self.tableWidget_1, self.tableWidget_2)
        MainWindow.setTabOrder(self.tableWidget_2, self.pushButton_logout)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))
        self.pushButton_inserir.setText(_translate("MainWindow", "INSERIR PESSOA"))
        self.pushButton_remove.setText(_translate("MainWindow", "REMOVER PESSOA"))
        self.pushButton_relatorio.setText(_translate("MainWindow", "IMPRIMIR RELATÓRIO"))
