# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lucas\Documents\GitHub\ShortProjects\Python\LoginApp\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 883)
        MainWindow.setStyleSheet("background-color: lightgreen;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelWelcome = QtWidgets.QLabel(self.centralwidget)
        self.labelWelcome.setGeometry(QtCore.QRect(460, 360, 161, 51))
        self.labelWelcome.setText("")
        self.labelWelcome.setObjectName("labelWelcome")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(970, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_logout.setFont(font)
        self.pushButton_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_logout.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_logout.setObjectName("pushButton_logout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))
